### PR TITLE
add external links to home page

### PR DESCRIPTION
**Pull request by hdenisenko**
addressing [this](https://github.com/codeformilwaukee/DECARCERATION-PLATFORM/issues/40) issue

Not going off any design specs (should i be??), so just did the best I could think of without knowing the final look of the page. Happy to make whatever edits are suggested!

### CODE REVIEW

**Comment by paul-rinaldi** [comment]
This is great, I added one change for readability. Please like this comments if you agree with my last commit, @hdenisenko then I'll close!

**Comment by hdenisenko** [comment]
@paul-rinaldi i don't see your change - i only see my commit here. but whatever your change is, i'm sure it's great! let me know whatever next steps i can start for this pr to go through.

**Comment by paul-rinaldi** [comment]
@hdenisenko 
I can't seem to push to your fork... I must have gotten something wrong. I reviewed the PR and left a comment, that's all. Thanks!

**Comment by hdenisenko** [comment]
@paul-rinaldi made the updates but looks like i'm still failing some jobs? not sure why? was another pr supposed to have addressed that or should investigate it on my end?

**Pull request merged**
